spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enable: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect